locale: en-US
title: RICHARD CHEAM
description: My portfolio, technical blog, and paper review hub.
url: https://richardcheam.github.io
baseurl: ""
timezone: Europe/Paris

markdown: kramdown
permalink: pretty

collections:
  blog:
    output: true
    permalink: /blog/:path/
  paper_reviews:
    output: true
    permalink: /paper-reviews/:path/

plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

exclude:
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - Dockerfile
  - CONTRIBUTING.md

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
  - scope:
      path: "_blog"
      type: blog
    values:
      layout: default
  - scope:
      path: "_paper_reviews"
      type: paper_reviews
    values:
      layout: default
